version: "3.8"

services:
  postgres:
    image: postgres:17
    restart: always
    container_name: salonio-postgres
    environment:
      POSTGRES_DB: salonio
      POSTGRES_USER: salonio_user
      POSTGRES_PASSWORD: salonio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
